Upgrade config file from version 3-alpha to version 3
Addressing:
WARN[0000] Config version 3-alpha has been stabilized as 3, and 3-alpha is no longer supported. Run `operator-sdk alpha config-3alpha-to-3` to upgrade your PROJECT config file to version 3
Error: error reading configuration: version 3-alpha is not supported